import './style.css'
import './components/MovingWaves'
import './components/LandingSection'
import './components/ChurchSection'
import './components/PlaceSection'
import './components/GiftRegistrySection'
import './components/HotelRecommendationSection'
import './components/DressCodeSection'
import './components/ItinerarySection'

